name: Continuous Integration

on: [push, pull_request]

concurrency:
    group: ${{github.head_ref || github.ref}}
    cancel-in-progress: true

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]

                node-version: [16.x]
                pnpm-version: [6.32]

        runs-on: ${{ matrix.platform }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Install Dependencies
              run: npm run install:all

            - name: Lint Codebase
              run: npm run lint:all

            - name: Build Packages
              run: npm run build:packages

            - name: Build Application
              run: npm run build:application
