name: Release

on:
    release:
        types:
            - published

jobs:
    build:
        strategy:
            matrix:
                platform: [ubuntu-latest]

                node-version: [16.x]
                pnpm-version: [6.32]
                rust-version: [stable]

        runs-on: ${{ matrix.platform }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.rust-version }}

            - name: Install Ubuntu Dependencies
              if: ${{ matrix.platform == 'ubuntu-latest' }}
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

            - name: Install Web Application Dependencies
              run: npm run install:all

            - name: Build Packages
              run: npm run build:packages

            - name: Cache Web Application Version
              working-directory: ./packages/@svelte-in-motion-editor
              run: echo "APPLICATION_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: Build Web Application
              working-directory: ./packages/@svelte-in-motion-editor
              run: npm run build:application

            - name: Build Tauri Application
              working-directory: ./packages/@svelte-in-motion-tauri
              run: npm run build:application

            - name: Upload Linux Artifacts
              if: ${{ matrix.platform == 'ubuntu-latest' }}
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ./packages/@svelte-in-motion-tauri/src-tauri/target/release/bundle/appimage/svelte-in-motion_${{ env.APPLICATION_VERSION }}_amd64.AppImage
                      ./packages/@svelte-in-motion-tauri/src-tauri/target/release/bundle/deb/svelte-in-motion_${{ env.APPLICATION_VERSION }}_amd64.deb
